name: FastAPI-GitHub-Heroku

env:
      HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI}}
      MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME}}
      MLFLOW_TRACKING_PASSWORD:  ${{ secrets.MLFLOW_TRACKING_PASSWORD}}
      MLFLOW_RUN_ID: ${{ secrets.MLFLOW_RUN_ID }}

on:
  push:
    branches:
    - main
    - source_code
  pull_request:
    branches:
    - main

jobs:

  cd_pipeline:

      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
          git push heroku HEAD:main -fn